"""add_jira_subscriptions

Revision ID: 2eb47063a061
Revises: 547505cfa855
Create Date: 2026-01-16 21:41:38.340373

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2eb47063a061'
down_revision: str | Sequence[str] | None = '547505cfa855'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_last_seen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.String(length=32), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jira_lastseen_user_project', 'jira_last_seen', ['user_id', 'project_key'], unique=True)
    op.create_index(op.f('ix_jira_last_seen_user_id'), 'jira_last_seen', ['user_id'], unique=False)
    op.create_table('jira_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_key', sa.String(length=32), nullable=False),
    sa.Column('issue_key', sa.String(length=64), nullable=True),
    sa.Column('watch_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jira_sub_user_project', 'jira_subscriptions', ['user_id', 'project_key'], unique=False)
    op.create_index(op.f('ix_jira_subscriptions_project_key'), 'jira_subscriptions', ['project_key'], unique=False)
    op.create_index(op.f('ix_jira_subscriptions_user_id'), 'jira_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jira_subscriptions_user_id'), table_name='jira_subscriptions')
    op.drop_index(op.f('ix_jira_subscriptions_project_key'), table_name='jira_subscriptions')
    op.drop_index('idx_jira_sub_user_project', table_name='jira_subscriptions')
    op.drop_table('jira_subscriptions')
    op.drop_index(op.f('ix_jira_last_seen_user_id'), table_name='jira_last_seen')
    op.drop_index('idx_jira_lastseen_user_project', table_name='jira_last_seen')
    op.drop_table('jira_last_seen')
    # ### end Alembic commands ###
